title: >-
  https://docs.google.com/spreadsheets/d/1OMmCjg47atQYcwnR6LlYECaswYi-hZnCEET4gXGIlaQ/edit?usp=drivesd
description: >-
  https://docs.google.com/spreadsheets/d/1OMmCjg47atQYcwnR6LlYECaswYi-hZnCEET4gXGIlaQ/edit?usp=drivesdk&disco=AAAALAzQkvs
template:
  repo: >-
    https:docs.google.comspreadsheetsd1ommcjg47atqycwnr6llyecaswyi-hznceet4gxgilaqedituspdrivesd-template
  name: >-
    https:docs.google.comspreadsheetsd1ommcjg47atqycwnr6llyecaswyi-hznceet4gxgilaqedituspdrivesd
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
